### ISSUE TITLE
Error Downloading Torrent with qbittorrent

### ISSUE THREAD

**Issue by norm-git** [alexpdev/TorrentFile-DEV#23]
Here is Torrent File created with torrentfile. I added some tracker but the download doesn't start, why

You can try download here torrent
https://00s23-webgx4.wrench.gq/38436/ufc.torrent

**Comment by alexpdev** [comment]
Sorry,  This repo will soon be an archive.  The official repo can be found at https://github.com/alexpdev/torrentfile.

As for your question.  This was due to a bug that has since been patched and fixed in the official repo.  

Thanks
